# Generated by Django 3.1.3 on 2020-11-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Function',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Имя функции')),
                ('call_spec', models.CharField(max_length=512, verbose_name='Вызов с именами аругментов')),
                ('args', models.TextField(null=True, verbose_name='Описание агрументов')),
                ('description', models.TextField(null=True, verbose_name='Описание функции')),
                ('examples', models.TextField(null=True, verbose_name='Примеры вызовов')),
            ],
        ),
    ]
